### ISSUE TITLE
Site deployment failed

### ISSUE THREAD

**Issue by skgupta507** [Zeddxx/moobie#8]
Hello @Zeddxx  
I tried hosting this site on vercel but the deployment failed can u guide me how to successfully deploy this so that it works. 
It's an awesome website so i thought to deploy my own instance.

**Comment by Zeddxx** [comment]
@skgupta507 what error are you facing?

**Comment by Zeddxx** [comment]
@skgupta507 The error you are encountering is because the environment variable MOOBIE_API_URL is missing, as it requires a backend connection.

**Comment by Zeddxx** [comment]
@skgupta507  Also, before pushing to Vercel, try building the application on your local system to identify any specific errors.

**Comment by skgupta507** [comment]
> @skgupta507 The error you are encountering is because the environment variable MOOBIE_API_URL is missing, as it requires a backend connection.

But there is no .env file  
if u can provide the api link and the env template it would help me greatly

**Comment by skgupta507** [comment]
> @skgupta507 Also, before pushing to Vercel, try building the application on your local system to identify any specific errors.

@Zeddxx  i tried it first on my local machine i was getting the same error So i thought let me try vercel. i even tried netlify when i encountered the same error i opened the issue for ur help

**Comment by Zeddxx** [comment]
i have added .env example as for the moobie api its a simple scrapper.

**Comment by Zeddxx** [comment]
@skgupta507 I have hidden the error as it was looking annoying to me. 😅

**Comment by Zeddxx** [comment]
@skgupta507 what I did was I am scrapping dramacool.com.pa and from title I am getting their I’d from consumetAPI.

just deploy your own instance of consumetApi and let me know.

**Comment by skgupta507** [comment]
> @skgupta507 what I did was I am scrapping dramacool.com.pa and from title I am getting their I’d from consumetAPI.
> 
> just deploy your own instance of consumetApi and let me know.

@Zeddxx  i already have a consumet api hosted here is the link https://api-consumet-org-olive.vercel.app/

**Comment by Zeddxx** [comment]
Now use nextjs api router to work as a backend and false at `src/api/home/route.ts`.
Inside that file paste this:
`async function scrapeCarousel() {
  try {
    const response = await axios.get(`https://dramacool.com.pa/`);
    const $ = load(response.data);

    const carouselSlider: CarouselSliderTypes[] = [];

    const carouselElement = $("div.ls-slide");

    carouselElement.each((index, element) => {
      const img = $(element).find("img");
      // const aTag = $(element).find("a");

      const imageSrc = img.attr("src") || "";
      const title = img.attr("title") || "";
      // const href = aTag.attr("href") || "";
      const dramaId = title.toLowerCase().split(" ").join("-");
      // const dramaId = href.match(/drama-detail\/(.*)$/)?.[1] || "";

      carouselSlider.push({ dramaId, title, imageSrc, id: "", poster: "" });
    });

    if (carouselSlider.length > 0) {
      const promises = carouselSlider.map(async (element) => {
        const data = await scrapeSearchResults(element.title, 1);
        const dramaId = data.results[0].id;
        const id = dramaId.replace("drama-detail/", "");
        const poster = data.results[0].image;
        return { ...element, id, poster };
      });

      const updatedCarouselSlider = await Promise.all(promises);

      carouselSlider.splice(0, carouselSlider.length, ...updatedCarouselSlider);
    }
    // Scrape recent dramas
    const dramas: DramaInfo[] = [];

    const recentDramaContainer = $("div.left-tab-1 ul.list-episode-item li");

    recentDramaContainer.each((index, element) => {
      const title = $(element).find(".title").text();

      const href = $(element).find("a").attr("href") || "";
      const idMatch = href.match(/\/([^/]+-\d+)-episode-\d+/);
      const id = idMatch ? idMatch[1] : ""; // Extract the desired ID
      const type = $(element).find(".type").text();
      const time = $(element).find(".time").text().trim();
      const episode = $(element).find(".ep").text();
      const poster = $(element).find("a.img img").attr("data-original") || "";

      dramas.push({ title, id, type, time, episode, poster });
    });

    // merging with id
    if (dramas.length > 0) {
      const promises = dramas.map(async (drama) => {
        const data = await scrapeSearchResults(drama.title, 1);
        const dramaId = data.results[0].id;
        const id = dramaId.replace("drama-detail/", "");

        return { ...drama, id };
      });

      const updatedDramasWithId = await Promise.all(promises);
      dramas.splice(0, dramas.length, ...updatedDramasWithId);
    }

    // Scrape recent movies
    const recentMovies: RecentMovies[] = [];
    const recentMoviesContainer = $("div.left-tab-2 > ul.list-episode-item");

    recentMoviesContainer.find("li").each(function () {
      const title = $(this).find(".title").text().trim();
      const id = title
        .toLowerCase()
        .split(" ")
        .join("-")
        .replace("(", "")
        .replace(")", "");
      const time = $(this).find(".time").text().trim();
      const type = $(this).find(".type").text().trim();
      const poster = $(this).find("img").attr("data-original") || "";
      const episode = $(this).find(".ep").text().trim();

      recentMovies.push({
        id: id,
        title: title,
        time: time,
        type: type,
        poster: poster,
        episode: episode,
      });
    });

    if (recentMovies.length > 0) {
      const promises = recentMovies.map(async (movie) => {
        const data: SearchQueryResultTypes = await scrapeSearchResults(movie.title, 1);
        const dramaId = data?.results[0].id;
        const id = dramaId.replace("drama-detail/", "");
        return { ...movie, id };
      });

      const updatedMoviesWithId = await Promise.all(promises);
      recentMovies.splice(0, recentMovies.length, ...updatedMoviesWithId);
    }
    return { carouselSlider, recentDrama: dramas, recentMovies };
  } catch (error) {
    console.error("Error scraping homepage:", error);
    throw error; // Rethrow the error to be handled by the caller
  }
}

export default scrapeCarousel; `

**Comment by skgupta507** [comment]
@Zeddxx  sorry for disturbing u so much but i got this error during deployment.
Failed to compile.
--
 
 ./src/api/home/route.ts
 1:78  Error: Parsing error: ',' expected.

 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules

 Error: Command "npm run build" exited with 1

**Comment by Zeddxx** [comment]
@skgupta507 Can you give me access as collaborator ?

**Comment by skgupta507** [comment]
> `async function scrapeSearchResults(query: string, page: number): Promise<SearchQueryResultTypes> { try { const { data } = await axios.get<SearchQueryResultTypes>(BASE_API_URI + `/movies/dramacool/${query}?page=${page}`) const newData = data.results.map((result) => ({ ...result, id: result.id.replace("drama-detail/", "") })) return { ...data, results: newData }; } catch (error) { throw createHttpError.BadRequest("Something went wrong! please try again later.") } }
> 
> export default scrapeSearchResults; `

sure let me do that.

**Comment by Zeddxx** [comment]
> > @skgupta507 Can you give me access as collaborator ?
> 
> @Zeddxx i have added u as an collaborator accept the invitation.

Got it lemme try to fix it.

**Comment by Zeddxx** [comment]
@skgupta507 i have only fixed the moobie home not other routes.

**Comment by Zeddxx** [comment]
@skgupta507 I will help you if I have time, but try to search for answers yourself, as this will make you good at coding.

**Comment by skgupta507** [comment]
Thanks for the help.
